spring.application.name=outdooractivity
spring.main.web-application-type=none
weather.api.key=PLACEHOLDER
weather.api.base-url=http://api.weatherapi.com/v1
weather.monitor.cron=*/10 * * * * *
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sender@example.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true